---
# tasks file for ansible-users-role

# install for root user
- import_tasks: root.yml

# install all other users
- import_tasks: users.yml
  when:
    - users is defined
    - users|length > 0

# check and install miniconda
- name: check for installation of Miniconda
  become: '{{ miniconda_escalate }}'
  stat:
    path: '{{  miniconda_conda_bin  }}'
  changed_when: false
  register: miniconda_conda_binary

- import_tasks: miniconda.yml
  when: miniconda_conda_binary.stat.exists
